### ISSUE TITLE
Use @actions/tool-cache in Cargo.installCached

### ISSUE THREAD

**Issue by alex** [actions-rs/core#31]
There's a TODO for this, but I figured it might be helpful to have an issue for this:

https://github.com/actions-rs/core/blob/29a296ec644ed19d68bb97cd056da3a453cf7ac2/src/commands/cargo.ts#L33-L35

The lack of caching makes `cargo-audit` very very slow :-(

I haven't played with `@actions/tool-cache` yet myself, but I imagine the solution is roughly calling `tc.find()`, if it returns something copy it to the right place, otherwise run the install and then call `tc.cacheFile()`.

**Comment by svartalf** [comment]
Hey, @alex, thanks for reminder, this thing definitely need a tracking issue.
Any executed `cargo install {pkg}` is slow right now, for example, same goes to [`actions-rs/cargo`](https://github.com/actions-rs/cargo#inputs) Action with `use-cross: true` input enabled, as it compiles `cross` on each execution.

This comment is a bit outdated, though, it seems that `@actions/tool-cache` package hardly can be applied here, as it is expected that the downloaded tool can be executed immediately, which is not the case for executables installed via the `cargo install`, as we need to compile them.

It might be possible to provide download URLs for some cargo subcommand (let's say, download it from the GitHub releases page, like with a `tarpaulin` code coverage tool), but it is not very handy and can't be applied to all possible options (`cargo-audit` being one of them), so we will end with the compilation once again.

I would like to add an opaque cache for compiled subcommands with the simple "if it is not in cache yet, compile it and put it in ther" flow, but at the moment it is blocked by https://github.com/actions/cache/issues/55
Cached tools might be evicted from the cache eventually and will eat some of that precious available cache space (~few megabytes per subcommand), but it seems to be the best option so far, as soon as linked issue will be resolved.

**Comment by nickelc** [comment]
I'm working on GitHub release installers for some commands (`cargo-make`, `cargo-web`, `mdbook`).
https://github.com/nickelc/actions-rs-core/tree/installers

The installers use `@actions/tool-cache` to download and put the binary into the tool cache but a persistent cache is only supported on self-hosted runners.
